#ifndef __MOONLIGHT_CONTROLLER_DEFINITIONS_H__
#	define __MOONLIGHT_CONTROLLER_DEFINITIONS_H__

#	if defined(MOONLIGHT_CONTROLLER_LIBRARY)
#		define MOONLIGHT_CONTROLLER_PRIVATE public
#	else
#		define MOONLIGHT_CONTROLLER_PRIVATE private
#	endif

#endif
